# Generated by Django 6.0.6 on 2026-06-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Intervención', 'verbose_name_plural': 'Intervenciones'},
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_programada', '-fecha_creacion'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
    ]
