# Generated by Django 6.0.6 on 2026-06-20 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('DADO_DE_BAJA', 'Dado de baja')], default='OPERATIVO', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('frecuencia_mantenimiento_dias', models.PositiveIntegerField(default=90)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.categoriaequipo')),
            ],
        ),
    ]
