# Generated by Django 6.0.6 on 2026-06-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaequipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria de Equipo', 'verbose_name_plural': 'Categorias de Equipos'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo_interno'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]