# Generated by Django 6.0.6 on 2026-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_categoriaequipo_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaequipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Equipo', 'verbose_name_plural': 'Categorías de Equipos'},
        ),
    ]
