# Generated by Django 6.0.6 on 2026-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_categoriaequipo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Equipo',
                'verbose_name_plural': 'Secuencias de Equipo',
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
