# Generated by Django 6.0.6 on 2026-07-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_secuenciaequipo_alter_equipo_codigo_interno'),
    ]

    operations = [
    ]
